FROM nginx:1.15.0-alpine


# substitui o default.conf por um com o redirecionamento para o node
COPY default.conf /etc/nginx/conf.d/default.conf

#ENTRYPOINT [ "/docker-entrypoint.sh" ]
#CMD ["nginx", "-g", "deamon off;"]

